"""
SurrogateODE: Two-compartment pharmacokinetic/pharmacodynamic model.

This is the computational core of each PatientAgent in Layer 2.

Architecture decision (from spec):
  BioGears is the ground-truth reference. This ODE is a fast surrogate
  calibrated to match BioGears output across a parameter grid. During RL
  training the ODE runs at each env.step() (microseconds per call).
  Final policies are validated back against BioGears.

Two-compartment PK model:
  Central compartment (plasma + well-perfused tissues):
    dCc/dt = (F * ka * D * exp(-ka*t)) / Vc - (CL/Vc)*Cc - (Q/Vc)*(Cc - Cp)
  Peripheral compartment (muscle, fat, slowly-perfused tissues):
    dCp/dt = (Q/Vp) * (Cc - Cp)

PD model (Emax/Hill equation):
  Effect = Emax * Cc^n / (EC50^n + Cc^n)
  Toxicity = f(Cmax, AUC, time above toxic threshold)

All parameters come from ADMETProperties.to_pkpd_params() — nothing
is hardcoded. Species scaling is applied by AllometricScaler.

Units:
  Time     : hours
  Dose     : mg/kg
  Conc     : mg/L (= μg/mL)
  Volume   : L/kg
  Clearance: L/h/kg

References:
  - Rowland & Tozer, Clinical Pharmacokinetics (4th ed.)
  - Gabrielsson & Weiner, Pharmacokinetic/Pharmacodynamic Data Analysis
  - BioGears validation: https://biogearsengine.com/documentation/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
from scipy.integrate import solve_ivp


# ---------------------------------------------------------------------------
# ODE state container
# ---------------------------------------------------------------------------

@dataclass
class PKPDState:
    """
    Snapshot of the PK/PD state at a single time point.

    Attributes
    ----------
    t : float
        Time in hours since dose administration.
    Cc : float
        Central compartment concentration (mg/L).
    Cp : float
        Peripheral compartment concentration (mg/L).
    cumulative_AUC : float
        Area under the plasma concentration curve (mg·h/L).
    Cmax : float
        Maximum observed concentration so far (mg/L).
    effect : float
        Pharmacodynamic effect in [0, 1] (Emax model).
    toxicity_score : float
        Toxicity signal in [0, 1] (based on Cmax/AUC vs thresholds).
    above_MTC : bool
        True if current Cc > minimum toxic concentration.
    below_MEC : bool
        True if current Cc < minimum effective concentration.
    """
    t: float = 0.0
    Cc: float = 0.0
    Cp: float = 0.0
    cumulative_AUC: float = 0.0
    Cmax: float = 0.0
    effect: float = 0.0
    toxicity_score: float = 0.0
    above_MTC: bool = False
    below_MEC: bool = False

    def to_array(self) -> np.ndarray:
        """Returns the state as a float32 numpy array for RL observations."""
        return np.array([
            self.t,
            self.Cc,
            self.Cp,
            self.cumulative_AUC,
            self.Cmax,
            self.effect,
            self.toxicity_score,
            float(self.above_MTC),
            float(self.below_MEC),
        ], dtype=np.float32)

    STATE_DIM: int = 9  # length of to_array() output


@dataclass
class DoseEvent:
    """A single dose administration event."""
    time_h: float     # time of administration (hours)
    dose_mgkg: float  # dose in mg/kg
    route: str = "oral"   # "oral" | "iv_bolus" | "iv_infusion"


# ---------------------------------------------------------------------------
# Surrogate ODE
# ---------------------------------------------------------------------------

class SurrogateODE:
    """
    Two-compartment PK + Emax PD surrogate model.

    Parameters
    ----------
    pkpd_params : dict
        From ADMETProperties.to_pkpd_params(). Keys:
          ka, F, CL, Vc, Vp, Q, PPB, fu
    pd_params : dict, optional
        Pharmacodynamic parameters. Keys:
          Emax  — maximum effect [0, 1], default 0.9
          EC50  — half-maximal effective concentration (mg/L), default 1.0
          n     — Hill coefficient, default 1.5
          MTC   — minimum toxic concentration (mg/L), default 5.0
          MEC   — minimum effective concentration (mg/L), default 0.2
    body_weight_kg : float
        Patient body weight. Used for dose conversion.
    biogears_calibration : dict, optional
        Calibration factors from BioGears fitting. If provided, these
        multiplicatively adjust the ODE parameters to match BioGears output.
        Generated by BiogearsSurrogateCalibrator (see pk_pd/calibration.py).

    Notes
    -----
    For IV bolus dosing: F=1.0, ka is bypassed (dose appears instantly in Cc).
    For oral dosing: absorption is modeled via the depot compartment.
    For IV infusion: rate-based input; not yet implemented in v1.
    """

    # DEFAULT_PD_PARAMS is intentionally NOT used as a silent fallback.
    # All PD parameters must originate from ADMETProperties.to_pd_params().
    # This sentinel dict is exposed only for unit-test scaffolding; the
    # PatientAgent always passes drug-derived pd_params.
    DEFAULT_PD_PARAMS = {
        "Emax": 0.9,
        "EC50": 1.0,
        "n":    1.5,
        "MTC":  5.0,
        "MEC":  0.2,
    }

    def __init__(
        self,
        pkpd_params: dict,
        pd_params: dict = None,
        body_weight_kg: float = 70.0,
        biogears_calibration: dict = None,
    ):
        self.bw = body_weight_kg
        self.pk = dict(pkpd_params)
        # PD params must come from to_pd_params() in production.
        # In tests that pass explicit pd_params, those are used directly.
        if pd_params is not None:
            self.pd = dict(pd_params)
        else:
            # No drug profile available — use DEFAULT only in test/stub contexts.
            self.pd = dict(self.DEFAULT_PD_PARAMS)

        # DDI: CYP-mediated clearance inhibition factor.
        # Set via set_cyp_inhibition_factor(); initially no interaction.
        self._cl_inhibition_factor: float = 1.0   # effective CL = CL / factor

        # Apply BioGears calibration if available
        if biogears_calibration:
            self._apply_calibration(biogears_calibration)

        # Simulation state
        self._dose_events: List[DoseEvent] = []
        self._state_history: List[PKPDState] = []
        self._current_state = PKPDState()
        self._prev_t = 0.0
        self._depot = 0.0   # Absorption compartment (oral dose buffer)

    def _apply_calibration(self, cal: dict):
        """Multiply ODE parameters by BioGears-derived calibration factors."""
        for key, factor in cal.items():
            if key in self.pk:
                self.pk[key] *= factor

    # ------------------------------------------------------------------
    # Dosing
    # ------------------------------------------------------------------

    def administer_dose(
        self,
        dose_mgkg: float,
        time_h: float = 0.0,
        route: str = "oral",
    ):
        """
        Schedule a dose event.

        For oral dosing, the dose enters the depot compartment.
        For IV bolus, it goes directly into the central compartment.

        Parameters
        ----------
        dose_mgkg : float
            Dose in mg/kg body weight.
        time_h : float
            Time of administration in hours.
        route : str
            'oral' or 'iv_bolus'.
        """
        event = DoseEvent(time_h=time_h, dose_mgkg=dose_mgkg, route=route)
        self._dose_events.append(event)
        self._dose_events.sort(key=lambda e: e.time_h)

    # ------------------------------------------------------------------
    # ODE definition
    # ------------------------------------------------------------------

    # ------------------------------------------------------------------
    # DDI / CYP inhibition interface
    # ------------------------------------------------------------------

    def set_cyp_inhibition_factor(self, factor: float):
        """
        Set effective CL reduction due to CYP enzyme inhibition.

        This implements the static mechanistic DDI model (FDA M12 guidance):
            CL_eff = CL_nominal / inhibition_factor

        Where inhibition_factor = 1 + [I]_unbound / Ki
        (competitive inhibition; Rowland-Matin equation).

        Parameters
        ----------
        factor : float
            Inhibition factor ≥ 1.0.
            1.0 = no inhibition; 5.0 = 5-fold CL reduction (AUC 5×).
        """
        self._cl_inhibition_factor = float(max(factor, 1.0))

    def reset_cyp_inhibition(self):
        """Remove DDI effect (restore full clearance)."""
        self._cl_inhibition_factor = 1.0

    @property
    def effective_cl(self) -> float:
        """Current effective clearance after DDI adjustment (L/h/kg)."""
        return self.pk["CL"] / self._cl_inhibition_factor

    def _odes(self, t: float, y: np.ndarray, dose_events: list) -> np.ndarray:
        """
        Two-compartment ODE system.

        State vector y = [Depot, Cc, Cp, AUC]
          Depot — amount in absorption compartment (mg/kg)
          Cc    — central compartment concentration (mg/L)
          Cp    — peripheral compartment concentration (mg/L)
          AUC   — cumulative area under the curve (mg·h/L)

        Returns dy/dt.

        DDI: effective clearance = CL / _cl_inhibition_factor.
        This is updated externally by ComboDDIEnv at each time step using the
        perpetrator drug's current free concentration.
        """
        Depot, Cc, Cp, AUC = y
        Cc = max(Cc, 0.0)
        Cp = max(Cp, 0.0)
        Depot = max(Depot, 0.0)

        ka = self.pk["ka"]
        # Apply DDI-adjusted clearance (competitive inhibition model)
        CL = self.pk["CL"] / max(self._cl_inhibition_factor, 1.0)
        Vc = self.pk["Vc"]
        Vp = self.pk["Vp"]
        Q  = self.pk["Q"]

        # Absorption depot: first-order oral absorption
        dDepot = -ka * Depot

        # Absorption into central compartment
        absorption_rate = ka * Depot / Vc  # concentration/time

        # Central compartment:
        #   in  = absorption (oral) OR IV bolus (handled by initial conditions)
        #   out = elimination + transfer to peripheral
        dCc = absorption_rate - (CL / Vc) * Cc - (Q / Vc) * Cc + (Q / Vp) * Cp

        # Peripheral compartment: net transfer from central
        dCp = (Q / Vc) * Cc - (Q / Vp) * Cp

        # AUC integration (trapezoid via ODE)
        dAUC = Cc

        return np.array([dDepot, dCc, dCp, dAUC])

    # ------------------------------------------------------------------
    # Simulation
    # ------------------------------------------------------------------

    def simulate(
        self,
        duration_h: float,
        dt_h: float = 0.25,
        t_start: float = 0.0,
    ) -> List[PKPDState]:
        """
        Simulate the PK/PD model over a time window.

        Handles multiple dose events within the window via event-driven
        integration (stops and restarts the ODE at each dose event).

        Parameters
        ----------
        duration_h : float
            Simulation duration in hours.
        dt_h : float
            Output time step for state recording (hours). Default: 15 min.
        t_start : float
            Start time (for multi-episode continuations).

        Returns
        -------
        List[PKPDState]
            State history at each dt_h interval.
        """
        t_end = t_start + duration_h
        t_eval_full = np.arange(t_start, t_end + dt_h, dt_h)

        # Initial conditions: [Depot, Cc, Cp, AUC]
        if self._state_history:
            last = self._state_history[-1]
            y0 = np.array([self._depot, last.Cc, last.Cp, last.cumulative_AUC])
        else:
            y0 = np.array([0.0, 0.0, 0.0, 0.0])

        # Collect dose events in this window
        window_events = [
            e for e in self._dose_events
            if t_start <= e.time_h < t_end
        ]

        # Sort into segments by dose event times
        segment_starts = [t_start] + [e.time_h for e in window_events]
        segment_ends   = [e.time_h for e in window_events] + [t_end]

        all_states = []
        current_y = y0.copy()
        current_depot = y0[0]

        for seg_start, seg_end, *dose_before in zip(
            segment_starts, segment_ends,
            [None] + window_events
        ):
            # Apply dose at segment start (if any)
            if dose_before and dose_before[0] is not None:
                event = dose_before[0]
                if event.route == "oral":
                    current_y[0] += self.pk["F"] * event.dose_mgkg
                elif event.route == "iv_bolus":
                    current_y[1] += event.dose_mgkg / self.pk["Vc"]

            if seg_end <= seg_start:
                continue

            t_eval = t_eval_full[
                (t_eval_full >= seg_start) & (t_eval_full <= seg_end)
            ]
            if len(t_eval) < 2:
                t_eval = np.array([seg_start, seg_end])

            sol = solve_ivp(
                fun=self._odes,
                t_span=(seg_start, seg_end),
                y0=current_y,
                t_eval=t_eval,
                method="RK45",
                args=(window_events,),
                dense_output=False,
                rtol=1e-4,
                atol=1e-6,
            )

            if not sol.success:
                # If integration fails, use last known good state
                break

            current_y = sol.y[:, -1].copy()
            current_y = np.maximum(current_y, 0.0)

            # Record states at each time point
            for i, t in enumerate(sol.t):
                Depot_t = max(sol.y[0, i], 0.0)
                Cc_t    = max(sol.y[1, i], 0.0)
                Cp_t    = max(sol.y[2, i], 0.0)
                AUC_t   = max(sol.y[3, i], 0.0)

                state = self._make_state(t, Cc_t, Cp_t, AUC_t)
                all_states.append(state)

        # Update running state
        if all_states:
            self._depot = current_y[0]
            self._state_history.extend(all_states)
            self._current_state = all_states[-1]

        return all_states

    def _make_state(
        self,
        t: float,
        Cc: float,
        Cp: float,
        AUC: float,
    ) -> PKPDState:
        """Build a PKPDState with PD effects computed from current Cc."""
        # Running Cmax
        prev_cmax = self._current_state.Cmax if self._state_history else 0.0
        cmax = max(prev_cmax, Cc)

        # Emax PD model
        Emax = self.pd["Emax"]
        EC50 = self.pd["EC50"]
        n    = self.pd["n"]
        effect = (Emax * (Cc ** n)) / (EC50 ** n + Cc ** n + 1e-10)

        # Toxicity score: weighted by Cmax overage and AUC overage
        MTC = self.pd["MTC"]
        tox = 0.0
        if MTC > 0:
            # Sigmoid transition at MTC
            tox_cmax = float(np.clip(1 / (1 + np.exp(-3 * (Cc / MTC - 1))), 0, 1))
            tox_auc  = float(np.clip(AUC / (MTC * 24), 0, 1))  # 24h reference
            tox = 0.6 * tox_cmax + 0.4 * tox_auc

        MEC = self.pd["MEC"]
        return PKPDState(
            t=t,
            Cc=float(Cc),
            Cp=float(Cp),
            cumulative_AUC=float(AUC),
            Cmax=float(cmax),
            effect=float(effect),
            toxicity_score=float(tox),
            above_MTC=bool(Cc > MTC),
            below_MEC=bool(Cc < MEC),
        )

    # ------------------------------------------------------------------
    # Convenience
    # ------------------------------------------------------------------

    @property
    def current_state(self) -> PKPDState:
        return self._current_state

    def reset(self):
        """Reset simulation state (start a new episode)."""
        self._dose_events.clear()
        self._state_history.clear()
        self._current_state = PKPDState()
        self._prev_t = 0.0
        self._depot = 0.0
        self._cl_inhibition_factor = 1.0   # clear any DDI effect

    def get_summary_stats(self) -> dict:
        """Returns AUC, Cmax, T>MTC fraction, Tmax."""
        if not self._state_history:
            return {}
        states = self._state_history
        Cc_vals = [s.Cc for s in states]
        tmax = states[np.argmax(Cc_vals)].t
        above_mtc = sum(s.above_MTC for s in states)
        return {
            "AUC":        states[-1].cumulative_AUC,
            "Cmax":       states[-1].Cmax,
            "Tmax_h":     tmax,
            "T_above_MTC_frac": above_mtc / max(len(states), 1),
            "mean_effect": np.mean([s.effect for s in states]),
            "peak_toxicity": max(s.toxicity_score for s in states),
        }

